config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :notes
  resources :workers

  root 'home#index'
get 'about' => 'about#about'
delete 'sign_out' => 'devise/sessions#destroy'
  

end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :worker
  validates :note_text, length: { maximum: 100 }, 
  presence: true
  validates :meeting_hour, length: { maximum: 100 },
  presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/worker.rb
class Worker < ActiveRecord::Base
  has_many :notes
  validates :name, :presence => true
  validates :surname, :presence => true
  validates :email, :presence => true
  validates :address, :presence => true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def about 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!, except: [:index,:show, :about]
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.all
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      flash[:notice] = ""
      redirect_to :action => 'index'
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:worker_id, :meeting_hour, :note_text)
    end
end

app/controllers/workers_controller.rb
class WorkersController < ApplicationController
  before_action :set_worker, only: [:show, :edit, :update, :destroy]

  # GET /workers
  # GET /workers.json
  def index
    @workers = Worker.all
  end

  # GET /workers/1
  # GET /workers/1.json
  def show
  end

  # GET /workers/new
  def new
    @worker = Worker.new
  end

  # GET /workers/1/edit
  def edit
  end

  # POST /workers
  # POST /workers.json
  def create
    @worker = Worker.new(worker_params)

    respond_to do |format|
      if @worker.save
        format.html { redirect_to @worker, notice: 'Worker was successfully created.' }
        format.json { render :show, status: :created, location: @worker }
      else
        format.html { render :new }
        format.json { render json: @worker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workers/1
  # PATCH/PUT /workers/1.json
  def update
    respond_to do |format|
      if @worker.update(worker_params)
        format.html { redirect_to @worker, notice: 'Worker was successfully updated.' }
        format.json { render :show, status: :ok, location: @worker }
      else
        format.html { render :edit }
        format.json { render json: @worker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workers/1
  # DELETE /workers/1.json
  def destroy
    @worker.destroy
    respond_to do |format|
      format.html { redirect_to workers_url, notice: 'Worker was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_worker
      @worker = Worker.find(params[:id])  
    rescue ActiveRecord::RecordNotFound
      flash[:notice] = ""
      redirect_to :action => 'index'

      
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def worker_params
      params.require(:worker).permit(:name, :surname, :email, :address)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/views/about/about.html.erb
<!DOCTYPE html>
<html>
<head>
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

<nav class="navbar navbar-light" style="background-color: #b3b3e6;">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Zarządzanie pracownikami</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="<%= root_path %>">Strona główna</a></li>
      <li><a href="<%= about_path %>">O twórcy</a></li>
      <li><a href="<%= workers_path %>">Pracownicy</a></li>
      <li><a href="<%= notes_path %>">Notatki</a></li>
    </ul>

  
  <ul class="nav navbar-nav navbar-right" style="background-color: #9999ff;">
      <% if user_signed_in? %>
    <li><%= link_to current_user.email, edit_user_registration_path %></li>
            <li><%= link_to "Wyloguj się", destroy_user_session_path, method: :delete %></li>
            <% else %>
            <li ><a href="<%= new_user_registration_path %>">Zarejestruj się</a></li>
            <li ><a href="<%= new_user_session_path %>">Zaloguj się</a></li>
            <% end %>
          </ul>
   </div>
</nav>  


<h1>Twórca aplikacji</h1>
<p>
  Kacper Korniak, III rok Informatyka, studia stacjonarne
  </p>
  <body class="container" style="background-color:	#cccccc">
<%= yield %>

</body>

</html>

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
<head>


<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %> 
<%= csrf_meta_tags %>


<nav class="navbar navbar-light" style="background-color: #b3b3e6;">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Zarządzanie pracownikami</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="<%= root_path %>">Strona główna</a></li>
      <li><a href="<%= about_path %>">O twórcy</a></li>
      <li><a href="<%= workers_path %>">Pracownicy</a></li>
      <li><a href="<%= notes_path %>">Notatki</a></li>
    </ul>

  
  <ul class="nav navbar-nav navbar-right" style="background-color: #9999ff;">
      <% if user_signed_in? %>
    <li><%= link_to current_user.email, edit_user_registration_path %></li>
            <li><%= link_to "Wyloguj się", destroy_user_session_path, method: :delete %></li>
            <% else %>
            <li ><a href="<%= new_user_registration_path %>">Zarejestruj się</a></li>
            <li ><a href="<%= new_user_session_path %>">Zaloguj się</a></li>
            <% end %>
          </ul>
   </div>
</nav>  



</head>
  
  <style>
  .color1{
  background-color: #b3c6ff;
  padding: 0 10px;
}
      .color2{
  background-color: #99b3ff;
  padding: 0 10px;
}
    
        .color3{
  background-color: #809fff;
  padding: 0 10px;
}
          

  </style>
  
  <body class="container" style="background-color:	#cccccc">
<%= yield %>
    <div class="container">
     
        
            <div class="row ">
                <div class="col-6 col-md-4 black text-center">
                   <div class="color1">
                     <h3 align="center">
                       O aplikacji
                     </h1>
                     <br>
                    <p align="left">Aplikacja przeznaczona do zarządzania pracownikami firmy.</p>
                </div>
              </div>
                <div class="col-6 col-md-4">
                  <div class="color2">
                    <h3 align="center">
                      Zakres funkcjonalnosci
                    </h2>
                    <br>
                    <p>Z poziomu aplikacji możemy:</p>
                      <ul>
                        <li>dodawać nowych pracowników</li>
                        <li>edytować dane poszczególnej osobie</li>
                        <li>usuwać z listy pracowników</li>
                        <li>uzyskać wgląd do informacji o pracowniku</li>
                        <li>tworzyć notatki i przypisać je konkretnej osobie podając jej ID</li>
                    </ul>
                   
                </div>
              </div>
              <div class="col-6 col-md-4 ">
                <div class="color3">
                  <h3 align="center">
                    Dostęp kontrolowany
                  </h2>
                  <br>
                    <p>Aby uzyskać dostęp do wszystkich funkcji należy się zarejestrować. Osoba zalogowana może edytować, usuwać, dodawać nowe dane. 
                      W przypadku osoby niezalogowanej/niezarejestrowanej możliwy jest wgląd do samej listy oraz do poszczególnej osoby. Swoje konto możemy edytować np. zmieniać hasło.</p>
                </div>
            </div>
        </div>
    

  

</body>

  
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/notes/_form.html.erb
<%= form_for(@note) do |f| %>
  <% if @note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% @note.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :worker_id %><br>
    <%= f.number_field :worker_id %>
  </div>
  <div class="field">
    <%= f.label :meeting_hour %><br>
    <%= f.text_field :meeting_hour %>
  </div>
  <div class="field">
    <%= f.label :note_text %><br>
    <%= f.text_field :note_text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notes/edit.html.erb
<!DOCTYPE html>
<html>
<head>
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>


<nav class="navbar navbar-light" style="background-color: #b3b3e6;">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Zarządzanie pracownikami</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="<%= root_path %>">Strona główna</a></li>
      <li><a href="<%= about_path %>">O twórcy</a></li>
      <li><a href="<%= workers_path %>">Pracownicy</a></li>
      <li><a href="<%= notes_path %>">Notatki</a></li>
    </ul>

  
  <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
    <li><%= link_to current_user.email, edit_user_registration_path %></li>
            <li><%= link_to "Wyloguj się", destroy_user_session_path, method: :delete %></li>
            <% else %>
            <li ><a href="<%= new_user_registration_path %>">Zarejestruj się</a></li>
            <li ><a href="<%= new_user_session_path %>">Zaloguj się</a></li>
            <% end %>
          </ul>
   </div>
</nav>  


<h1>Editing note</h1>

<%= render 'form' %>
<br>
  
<body class="container" style="background-color:	#cccccc">
  <%= yield %>
</body>
  
<%= link_to('Wyswietl', @note, :class => 'btn btn-primary btn-md') %>
<%= link_to('Cofnij się', notes_path, :class => 'btn btn-primary btn-md') %>

  </html>

app/views/notes/index.html.erb
<!DOCTYPE html>
<html>
<head>
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>


<nav class="navbar navbar-light" style="background-color: #b3b3e6;">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Zarządzanie pracownikami</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="<%= root_path %>">Strona główna</a></li>
      <li><a href="<%= about_path %>">O twórcy</a></li>
      <li><a href="<%= workers_path %>">Pracownicy</a></li>
      <li><a href="<%= notes_path %>">Notatki</a></li>
    </ul>

  
  <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
    <li><%= link_to current_user.email, edit_user_registration_path %></li>
            <li><%= link_to "Wyloguj się", destroy_user_session_path, method: :delete %></li>
            <% else %>
            <li ><a href="<%= new_user_registration_path %>">Zarejestruj się</a></li>
            <li ><a href="<%= new_user_session_path %>">Zaloguj się</a></li>
            <% end %>
          </ul>
   </div>
</nav>  

<h1>Notatki</h1>

<table>
  <thead>
    <table class="table table-dark">
    <tr>
      <th>Pracownik</th>
      <th>Godzina</th>
      <th>Notatka</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notes.each do |note| %>
      <tr>
        
        <td><%= note.worker_id %></td>
        <td><%= note.meeting_hour %></td>
        <td><%= note.note_text %></td>
        <td><%= link_to('Pokaż', note, :class => 'btn btn-sm btn-primary')  %></td> 
        <% if user_signed_in? %>
        <td><%= link_to('Edytuj', edit_note_path(note), :class => 'btn btn-sm btn-primary')  %></td> 
        <td><%= link_to('Usuń', note, method: :delete, :class => 'btn btn-sm btn-primary', data: { confirm: 'Are you sure?' }) %></td>
         <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to('Nowa notatka', new_note_path, :class => 'btn btn-primary btn-md' )  %>

</head>

  <body class="container" style="background-color:	#cccccc">
<%= yield %>

</body>

app/views/notes/new.html.erb
<!DOCTYPE html>
<html>
<head>
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>


<nav class="navbar navbar-light" style="background-color: #b3b3e6;">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Zarządzanie pracownikami</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="<%= root_path %>">Strona główna</a></li>
      <li><a href="<%= about_path %>">O twórcy</a></li>
      <li><a href="<%= workers_path %>">Pracownicy</a></li>
      <li><a href="<%= notes_path %>">Notatki</a></li>
    </ul>

  
  <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
    <li><%= link_to current_user.email, edit_user_registration_path %></li>
            <li><%= link_to "Wyloguj się", destroy_user_session_path, method: :delete %></li>
            <% else %>
            <li ><a href="<%= new_user_registration_path %>">Zarejestruj się</a></li>
            <li ><a href="<%= new_user_session_path %>">Zaloguj się</a></li>
            <% end %>
          </ul>
   </div>
</nav>  

<h1>Nowa notatka</h1>

<%= render 'form' %>

  
 <br>
<%= link_to('Cofnij się', notes_path, :class => 'btn btn-primary btn-md' )  %>

</head>

  <body class="container" style="background-color:	#cccccc">
<%= yield %>

</body>

app/views/notes/show.html.erb
<!DOCTYPE html>
<html>
<head>
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>


<nav class="navbar navbar-light" style="background-color: #b3b3e6;">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Zarządzanie pracownikami</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="<%= root_path %>">Strona główna</a></li>
      <li><a href="<%= about_path %>">O twórcy</a></li>
      <li><a href="<%= workers_path %>">Pracownicy</a></li>
      <li><a href="<%= notes_path %>">Notatki</a></li>
    </ul>

  
  <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
    <li><%= link_to current_user.email, edit_user_registration_path %></li>
            <li><%= link_to "Wyloguj się", destroy_user_session_path, method: :delete %></li>
            <% else %>
            <li ><a href="<%= new_user_registration_path %>">Zarejestruj się</a></li>
            <li ><a href="<%= new_user_session_path %>">Zaloguj się</a></li>
            <% end %>
          </ul>
   </div>
</nav>  

<p id="notice"><%= notice %></p>

<p>
  <strong>Worker:</strong>
  <%= @note.worker_id %>
</p>

<p>
  <strong>Meeting hour:</strong>
  <%= @note.meeting_hour %>
</p>

<p>
  <strong>Note text:</strong>
  <%= @note.note_text %>
</p>
  
  </head>

  <body class="container" style="background-color:	#cccccc">
  <%= yield %>
    
    </html>

</body>
</html>

<%= link_to('Edytuj', edit_note_path(@note), :class => 'btn btn-primary btn-md') %>
<%= link_to('Cofnij się', notes_path, :class => 'btn btn-primary btn-md') %>

app/views/workers/_form.html.erb
<%= form_for(@worker) do |f| %>
  <% if @worker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@worker.errors.count, "error") %> prohibited this worker from being saved:</h2>

      <ul>
      <% @worker.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :surname %><br>
    <%= f.text_field :surname %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/workers/edit.html.erb
<!DOCTYPE html>
<html>
<head>
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>


<nav class="navbar navbar-light" style="background-color: #b3b3e6;">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Zarządzanie pracownikami</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="<%= root_path %>">Strona główna</a></li>
      <li><a href="<%= about_path %>">O twórcy</a></li>
      <li><a href="<%= workers_path %>">Pracownicy</a></li>
      <li><a href="<%= notes_path %>">Notatki</a></li>
    </ul>

  
  <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
    <li><%= link_to current_user.email, edit_user_registration_path %></li>
            <li><%= link_to "Wyloguj się", destroy_user_session_path, method: :delete %></li>
            <% else %>
            <li ><a href="<%= new_user_registration_path %>">Zarejestruj się</a></li>
            <li ><a href="<%= new_user_session_path %>">Zaloguj się</a></li>
            <% end %>
          </ul>
   </div>
</nav>  

<h1>Zaktualizuj dane</h1>

  
<%= render 'form' %>
  <br>

  <%= link_to('Wyswietl', @worker, :class => 'btn btn-primary btn-md') %>
   <%= link_to('Cofnij się', workers_path, :class => 'btn btn-primary btn-md') %>

  
  </head>

  <body class="container" style="background-color:	#cccccc">
<%= yield %>
  </body>
    
    </html>

app/views/workers/index.html.erb
<!DOCTYPE html>
<html>
<head>
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>


<nav class="navbar navbar-light" style="background-color: #b3b3e6;">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Zarządzanie pracownikami</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="<%= root_path %>">Strona główna</a></li>
      <li><a href="<%= about_path %>">O twórcy</a></li>
      <li><a href="<%= workers_path %>">Pracownicy</a></li>
      <li><a href="<%= notes_path %>">Notatki</a></li>
    </ul>

  
  <ul class="nav navbar-nav navbar-right" style="background-color: #9999ff;">
      <% if user_signed_in? %>
    <li><%= link_to current_user.email, edit_user_registration_path %></li>
            <li><%= link_to "Wyloguj się", destroy_user_session_path, method: :delete %></li>
            <% else %>
            <li ><a href="<%= new_user_registration_path %>">Zarejestruj się</a></li>
            <li ><a href="<%= new_user_session_path %>">Zaloguj się</a></li>
            <% end %>
          </ul>
   </div>
</nav>  

<h1>Lista pracowników</h1>
  
  
  

<table>
  <thead>
    <table class="table table-dark">
    <tr>
      <th>Imie</th>
      <th>Nazwisko</th>
      <th>Email</th>
      <th>Adres zamieszkania</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @workers.each do |worker| %>
      <tr>
        
        <td><%= worker.name %></td>
        <td><%= worker.surname %></td>
        <td><%= worker.email %></td>
        <td><%= worker.address %></td>
        <td><%= link_to('Pokaż', worker, :class => 'btn btn-sm btn-primary')  %></td> 
        <% if user_signed_in? %>
        <td><%= link_to('Edytuj', edit_worker_path(worker), :class => 'btn btn-sm btn-primary')  %></td> 
        <td><%= link_to('Usuń', worker, method: :delete, :class => 'btn btn-sm btn-primary', data: { confirm: 'Are you sure?' }) %></td>
         <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
 
<br>
<%= link_to('Dodaj nowego pracownika', new_worker_path, :class => 'btn btn-primary btn-md' )  %>

  
  </head>

  <body class="container" style="background-color:	#cccccc">
<%= yield %>
  </body>
    
    </html>

app/views/workers/new.html.erb
<!DOCTYPE html>
<html>
<head>
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>


<nav class="navbar navbar-light" style="background-color: #b3b3e6;">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Zarządzanie pracownikami</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="<%= root_path %>">Strona główna</a></li>
      <li><a href="<%= about_path %>">O twórcy</a></li>
      <li><a href="<%= workers_path %>">Pracownicy</a></li>
      <li><a href="<%= notes_path %>">Notatki</a></li>
    </ul>

  
  <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
    <li><%= link_to current_user.email, edit_user_registration_path %></li>
            <li><%= link_to "Wyloguj się", destroy_user_session_path, method: :delete %></li>
            <% else %>
            <li ><a href="<%= new_user_registration_path %>">Zarejestruj się</a></li>
            <li ><a href="<%= new_user_session_path %>">Zaloguj się</a></li>
            <% end %>
          </ul>
   </div>
</nav>  

<h1>Nowy pracownik</h1>

<%= render 'form' %>

<br>
<%= link_to('Cofnij się', workers_path, :class => 'btn btn-primary btn-md') %>

  
  
   </head>

  <body class="container" style="background-color:	#cccccc">
  <%= yield %>
    
    

</body>

 </html>

app/views/workers/show.html.erb
<!DOCTYPE html>
<html>
<head>
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>


<nav class="navbar navbar-light" style="background-color: #b3b3e6;">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Zarządzanie pracownikami</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="<%= root_path %>">Strona główna</a></li>
      <li><a href="<%= about_path %>">O twórcy</a></li>
      <li><a href="<%= workers_path %>">Pracownicy</a></li>
      <li><a href="<%= notes_path %>">Notatki</a></li>
    </ul>

  
  <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
    <li><%= link_to current_user.email, edit_user_registration_path %></li>
            <li><%= link_to "Wyloguj się", destroy_user_session_path, method: :delete %></li>
            <% else %>
            <li ><a href="<%= new_user_registration_path %>">Zarejestruj się</a></li>
            <li ><a href="<%= new_user_session_path %>">Zaloguj się</a></li>
            <% end %>
          </ul>
   </div>
</nav>  


<p id="notice"><%= notice %></p>

<p>
  <strong>Imie:</strong>
  <%= @worker.name %>
</p>

<p>
  <strong>Nazwisko:</strong>
  <%= @worker.surname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @worker.email %>
</p>

<p>
  <strong>Adres:</strong>
  <%= @worker.address %>
</p>
  
    
<%= link_to('Edytuj', edit_worker_path(@worker), :class => 'btn btn-primary btn-md') %>
<%= link_to('Cofnij się', workers_path, :class => 'btn btn-primary btn-md') %>

  </head>

  <body class="container" style="background-color:	#cccccc">
  <%= yield %>
    
    </html>

</body>